### PR TITLE
added the workflow as mentioned in issue #68

### LINKED ISSUE #68: 💡[FEATURE]: Workflow for Closing Old Issues
**Is your feature request related to a problem? Please describe.**
Over time, repositories can accumulate a large number of open issues, including some that may no longer be relevant or actively worked on. Manually closing these old issues can be time-consuming and tedious.

**Describe the solution you'd like**
I would like a workflow that automatically identifies and closes old issues based on certain criteria, such as no recent activity or being open for a specific duration.

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #68 

@SB2318 please review and merge this PR

### CODE REVIEW

**Review by SB2318 — COMMENTED** [review]
*  the workflow specified in the given code snippet is set to run on the Ubuntu platform. This is indicated by the runs-on: ubuntu-latest,
Windows
Please make it available for other platform as well, like **Windows(>8)**, **Linux**, **Mac**

* `# Provide the comment format in the instruction by comment for mentioning that particular issue`

* Do it for the main and develop branches (as they both are working branches). Previously the PRs, against the develop branch did not close issues automatically with the merge process done.

```
on:
  push:
    branches:
      - main
      
      #By default
```

**Comment by Asymtode712** [comment]
@SB2318 made the changes requested by you, please review and merge this PR

**Review by SB2318 — APPROVED** [review]

**Comment by SB2318** [comment]
> @SB2318 no problem, I know you have recieved instructions to do so

 See, this is not the issue, There are almost 18 to 19 thousands members in our **GSSOC'24** community, and thousands of participants. So we have to make our leaderboard fair for all the participants. 😇

Our purpose is to give all tech enthusiasts a good start with our open source programs. 

So, don't be sad, keep contributing! 😇❤

**Comment by Asymtode712** [comment]
@SB2318 Yeah, you are right👍❤

**Pull request merged**
