### PR TITLE
💡[Feature]: Redirect User to home page After Verification Analysis and Possibility measurement. #134

### LINKED ISSUE #134: 💡[Feature]: Redirect User to home page After  Verification
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently when user verifies his account he get redirected to registration page instead of that we can send him directly to home page. and As Soon as he click on the mail to verify his account he will recieve response Mail of User Email Verified Successfully.
And Can Navigate to Home page 

### Use Case

It will make app easy to use for user

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

Prepare an analysis and share it via mail or in discord respective project channel.

### PR DESCRIPTION
**Pull request by nishant0708**
#### PR Description
💡[Feature]: Redirect User to home page After Verification Analysis and Possibility measurement. 
-Ensured all the things required in Pr

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ y] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [ ] Frontend
- [y ] Backend
- [ ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot
Screenshot 2024-06-20 003549

#### Fixes (mention the issue number which this fixes)
#closes  #134 

#### Checklist
- [y ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [y ] I have optimized the file changes.
- [y ] I have added a snapshot of my work example.
- [y ] I have made a PR to the project's develop branch.

#### Undertaking
- [ y] My code follows the style guidelines of this project.
- [ y] I have performed a self-review of my code.
- [ y] I have commented my code, particularly in hard-to-understand areas.
- [ y] I have made corresponding changes to the documentation.
- [ y] I have checked for plagiarism and assure its authenticity.
- [ y] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [ y] I Agree

To make button functional Add your deeplink here on line 130
image

### CODE REVIEW

**Comment by SB2318** [comment]
Great work! Will update you soon!
Thank you @nishant0708

**Review by SB2318 — APPROVED** [review]
Change the mongodb url.

**Comment by nishant0708** [comment]
Wait a second doing it now

**Comment by nishant0708** [comment]
hey @SB2318 check it now

**Comment by nishant0708** [comment]
Hey @SB2318 does it require any other changes?

**Comment by SB2318** [comment]
> Hey @SB2318 does it require any other changes?

@nishant0708  Really a great job done by you! But the current situation is the project is facing a error related  the horror library
`react-native-reanimated` .

I need to fix that, then only I can merge your branch, and suggest you changes.

**Comment by nishant0708** [comment]
Okay thanks 👍👍

**Comment by vHarshita15** [comment]
I want to contribute . Please assign

**Review by SB2318 — COMMENTED** [review]
Add Script to redirect user in play-store if app is not installed,

For your reference:
```

<div class="container">
  <img src="https://imgur.com/I5lDXoI.png" alt="Logo" class="logo">
  <h1>Welcome ✅</h1>
  <p>Your account has been verified successfully.</p>
  <button onclick="openApp()">Open Your App</button>
</div>

<script>
  function openApp() {
    var appScheme = 'your-app-scheme://';
    var appStoreUrl = 'your-app-store-url';

    function redirectToApp() {
      window.location.href = appScheme;
    }

    function redirectToAppStore() {
      window.location.href = appStoreUrl;
    }

    // Check if the app is installed
    if (window.navigator.userAgent.match(/(iPhone|iPod|iPad|Android)/)) {
      // Attempt to open the app
      redirectToApp();

      // Set a timeout to redirect to the app store if the app fails to open
      setTimeout(function() {
        redirectToAppStore();
      }, 3000); // Adjust the timeout duration as needed
    } else {
      // Redirect to the app store
      redirectToAppStore();
    }
  }
</script>
```

Don't copy-paste the same, But you ca research, I want to established deep linking in mobile app.

**Comment by nishant0708** [comment]
hey @SB2318 I got it I will do it and raise pr by 6 Thanks

**Comment by nishant0708** [comment]
Hey @SB2318  please check it now it will work now without any trouble

**Pull request merged**
