### PR TITLE
Enhance Readme.md with Animated Emojis, Alignment Fixes, Project Snapshots, and Contributor Profile Pictures. #90

### PR DESCRIPTION
**Pull request by Aditijainnn**
#### PR Description
Updated Readme.md file by adding animated emojis , fixing allignment , adding snapshots of our project, dsiplaying pfp of contributors in contri section and many more updates

#### Type of Change
- [x] New feature (change which adds functionality)

#### Select your work-area
Readme.md

.

#### Add your Work Example
📷 Add a Snapshot

1. #### Fixes (mention the issue number which this fixes) #90  #118

#closes

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
-  [x]  My code follows the style guidelines of this project.
-  [x] I have performed a self-review of my code.
-  [x] I have commented my code, particularly in hard-to-understand areas.
-  [x] I have made corresponding changes to the documentation.
-  [x] I have checked for plagiarism and assure its authenticity.
-  [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

-  [x]  I Agree

### CODE REVIEW

**Review by SB2318 — COMMENTED** [review]
@Aditijainnn  Definitely it is a great contribution! 🎊 But I have seen some conflicts here, may be due to updation, please look into it.

* Keep Headers and Remove **Content**
 When Headers drop down open, then it will able to see the topics.

image

* Give dropdown header for each content topics

image


**Getting started** and also all content topics will be  go under <details/> and <summary/>.


*  For License, Do something like

image


* For contact us, Do something like

image

**Comment by Aditijainnn** [comment]
okay

**Comment by Aditijainnn** [comment]
@SB2318 
I have done all the changes you can view them

**Comment by SB2318** [comment]
@Aditijainnn You haven't understand the point. Let me know if u need a discussion.

**Comment by Aditijainnn** [comment]
> @Aditijainnn You haven't understand the point. Let me know if u need a discussion.



yes what other things need to get changed?

**Comment by SB2318** [comment]
@Aditijainnn 

image
please resolve the conflict

and ensure that no data loss.

image

No feature loss.

image


You can take your time

**Comment by Aditijainnn** [comment]
okay I will try since I'm relatively new to GitHub and the process of handling conflicts, I am trying it resolve them.

**Comment by SB2318** [comment]
> okay I will try since I'm relatively new to GitHub and the process of handling conflicts, I am trying it resolve them.

Let me know If I can help you.

**Comment by Aditijainnn** [comment]
ok

**Comment by SB2318** [comment]
@Aditijainnn bohut accha  kam kiya ap!  Just close this PR, update the branch, and then made your changes there, and raise a new PR.  At least let me merge the PR, then only you will receive your point.

**Comment by Aditijainnn** [comment]
> @Aditijainnn bohut accha kam kiya ap! Just close this PR, update the branch, and then made your changes there, and raise a new PR. At least let me merge the PR, then only you will receive your point.

okay

**Pull request closed without merging**
