### PR TITLE
6 articles into Spanish Language.

### PR DESCRIPTION
**Pull request by Damini2004**
#### PR Description
6 articles into Spanish Language.

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#212 

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Comment by Damini2004** [comment]
@SB2318 Review and tell me is their any kind of conflicts ? after that i will do another translation of article too.

**Comment by SB2318** [comment]
> @SB2318 Review and tell me is their any kind of conflicts ? after that i will do another translation of article too.

image

Why there so many commit?

**Comment by SB2318** [comment]
> > @SB2318 Review and tell me is their any kind of conflicts ? after that i will do another translation of article too.
> 
> image
> 
> Why there so many commit?

did you run something like this.

git checkout -b develop

**Comment by Damini2004** [comment]
Yes

**Comment by Damini2004** [comment]
@SB2318 i should not have to create branch ?

**Comment by Damini2004** [comment]
@SB2318 as you told to update it with latest commit

**Comment by SB2318** [comment]
> @SB2318 i should not have to create branch ?


> @SB2318 as you told to update it with latest commit

I have shared the commit link also.

**Comment by Damini2004** [comment]
@SB2318 now what to do ?

**Comment by Damini2004** [comment]
guide me

**Comment by SB2318** [comment]
> > @SB2318 i should not have to create branch ?
> 
> > @SB2318 as you told to update it with latest commit
> 
> I have shared the commit link also.

image

These commit history  haven't found in your PR.

**Comment by SB2318** [comment]
> > > @SB2318 i should not have to create branch ?
> > 
> > 
> > > @SB2318 as you told to update it with latest commit
> > 
> > 
> > I have shared the commit link also.
> 
> image
> 
> These commit history haven't found in your PR.

Although, I understand the problem, Give me few hours.
I will suggest you the steps, which you have to follow to create a successful PR.

**Comment by Damini2004** [comment]
@SB2318 Sure, i translate the rest articles.

**Comment by SB2318** [comment]
> @SB2318 Sure, i translate the rest articles.

aur kuch nehi karna, ap thodasa relax karo. Abhi kuch karoge to problem bar jayega.

**Comment by Damini2004** [comment]
> > @SB2318 Sure, i translate the rest articles.
> 
> aur kuch nehi karna, ap thodasa relax karo. Abhi kuch karoge to problem bar jayega.

Ok mam 
Once you got solution then tell me

**Comment by Damini2004** [comment]
@SB2318 Can i work on #222 because i am converting it into spanish so it might be more easy to convert it into tamil,etc language too.

**Comment by SB2318** [comment]
> @SB2318 Can i work on #222 because i am converting it into spanish so it might be more easy to convert it into tamil,etc language too.

See, Your problem was that, at the time of forking the repo, you made this as checked.


image

For this reason, you do not have other branches. But there are 4 branches in the repository with 2 active branches.
When I told you to check out another active branch and add your changes there, you could not find it and made checkout from the main branch.

This is why many changes come as well as the effective modifications you can't include.
So, I can't consider it as an effective contribution.

**Comment by SB2318** [comment]
> > @SB2318 Can i work on #222 because i am converting it into spanish so it might be more easy to convert it into tamil,etc language too.
> 
> See, Your problem was that, at the time of forking the repo, you made this as checked.
> 
> image
> 
> For this reason, you do not have other branches. But there are 4 branches in the repository with 2 active branches. When I told you to check out another active branch and add your changes there, you could not find it and made checkout from the main branch.
> 
> This is why many changes come as well as the effective modifications you can't include. So, I can't consider it as an effective contribution.

Now come back to the point what you have to do.

(i) Store your changes locally.
(ii) Delete the repo & fork the develop branch.
(iii) There you will find 13 English articles, out of which you translate 6 articles, commit your changes
(iv) Create PR against the develop branch.

**Pull request closed without merging**
