### PR TITLE
Issue #14 Fixed : Create Application Logo

### PR DESCRIPTION
**Pull request by BHS-Harish**
Hey @SB2318 

Issue #14  Fixed

Logo added in src/assets folder.
Please verify and merge it.
Sorry for the delay.

Thanks for assigning the issue.

### CODE REVIEW

**Comment by SB2318** [comment]
@BHS-Harish Please rebase your commits into single one.

**Comment by BHS-Harish** [comment]
Hello @SB2318 

I rebased my commits 
please check it

Thank you

**Review by SB2318 — APPROVED** [review]
Bohut sara file changes kar diya, thik hain abhi project start nehi hua, aage se thoda dhiyan rakhna.

**Comment by BHS-Harish** [comment]
> Bohut sara file changes kar diya, thik hain abhi project start nehi hua, aage se thoda dhiyan rakhna.

Sorry i can't understand

**Pull request merged**
