### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by SharmaNishchay**
Added MIT license to the project

### CODE REVIEW

**Comment by SB2318** [comment]
Hello @SharmaNishchay 

Welcome to **Gssoc'24** 🎉🥳.

And Thanks for selecting this project.

Let me complete the setup process with respective mentors and organizers.

Will get back to you soon.

**Comment by Yaswanthtoga** [comment]
Hi @SB2318 , Good Day!
Can you confirm me that whether this project will start from scratch, I mean start from idea building to product building.

**Comment by SB2318** [comment]
@Yaswanthtoga Don't worry, keep patience. 😇

**Comment by SB2318** [comment]
Hello @SharmaNishchay 
Thanks for your contribution! 
Please create a new issue on this, and after that make a PR, with the **Gssoc** label. 

Please mention the respective issue with your PR like 

fixes #23

**Pull request closed without merging**
