### PR TITLE
Understanding Allergies and How to Manage Them ( English & Hindi )

### PR DESCRIPTION
**Pull request by Asymtode712**
#### PR Description

This PR adds two comprehensive markdown files, "Understanding Allergies and How to Manage Them" in English and Hindi, to the our repository. These files provide detailed insights into the immune system's response, common allergens, symptoms, diagnosis, and effective management strategies for allergies.

#### Type of Change

- [X] Documentation update

#### Select your work-area

- [X] Documentation

#### Related Issue

Issue: #296 

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
closes ##296 

#### Checklist
- [X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] I have checked for plagiarism and assure its authenticity.
- [X] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [X] I Agree

### CODE REVIEW

**Comment by Asymtode712** [comment]
@SB2318 Please review and merge this PR

**Review by SB2318 — COMMENTED** [review]
Very good! Could you please include some suitable images to help with visualization?

**Comment by Asymtode712** [comment]
@SB2318 Sure....

**Comment by Asymtode712** [comment]
@SB2318 I have added the images, please check and merge it if it is good to go

**Review by SB2318 — APPROVED** [review]
Good Work!

**Pull request merged**
