### PR TITLE
💡[Feature]: Article API creation #156

### LINKED ISSUE #156: 💡[Feature]: Article API creation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

CRUD Method  (GET, POST, UPDATE, DELETE)

You will responsible for two issues in our repo. (Article Schema preparation as well as CRUD method) 

### Use Case

Article Backend

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by nishant0708**
#### PR Description
Added  API for Articles

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [X ] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [ ] Frontend
- [X ] Backend
- [ ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example

Create article api working

Screenshot 2024-07-11 005430

Get all  articles  api working

Screenshot 2024-07-11 005701

backend storage of articles 

Screenshot 2024-07-11 005839

Get   articles by Id api working

Screenshot 2024-07-11 005931

Update  articles by Id api working

Screenshot 2024-07-11 010049

Delete articles by Id api working

Screenshot 2024-07-11 010115

#### Fixes #156 
#closes

#### Checklist
- [ X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [ X] I have optimized the file changes.
- [ X] I have added a snapshot of my work example.
- [X ] I have made a PR to the project's develop branch.

#### Undertaking
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have made corresponding changes to the documentation.
- [ X] I have checked for plagiarism and assure its authenticity.
- [ X] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [X ] I Agree

closes #156

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @SB2318 please check this pr whenever possible and let me know the changes

**Review by SB2318 — COMMENTED** [review]
* Validation Check missing
* getArticleByTitle
* getArticleByName
* Filter and Search functionality.
Will discuss

**Comment by nishant0708** [comment]
> * Validation Check missing
> * getArticleByTitle
> * getArticleByName
> * Filter and Search functionality.
>   Will discuss

Okay I will add validation for sure but get article by title an article by nama these are the functionality which can be handled from frontend but if you want it I can make it let me know route for that

**Comment by SB2318** [comment]
Okay, I will.

**Comment by nishant0708** [comment]
hey @SB2318  added authentication and added 2 more routes And for filter and searches i strongly recommend  you to handle that using frontend .. get all the articles and filter them however you need them because there are many things in article name title tags archive author name we cant create route for all

**Comment by SB2318** [comment]
Cool!

**Comment by SB2318** [comment]
But still, please wait. 😇

**Comment by nishant0708** [comment]
Yaa okay till then can I work on documentation issue 161?

**Comment by nishant0708** [comment]
hey @SB2318 any changes in this?

**Review by SB2318 — COMMENTED** [review]
Validation check and filter-search functionality left.

**Comment by nishant0708** [comment]
Hey @SB2318 validation is there

**Comment by nishant0708** [comment]
See middleware

**Comment by nishant0708** [comment]
> Validation check and filter-search functionality left.

And for filter and search I think it can be handled by frontend but if you need any specific route and filter please let me know

**Comment by SB2318** [comment]
will discuss later, please complete your rest assigned tasks.

**Review by SB2318 — CHANGES_REQUESTED** [review]
* Add search functionality, search by title & category & description

**Comment by nishant0708** [comment]
hey @SB2318  our Article Field doesn't have Any fields such as name , category ,description in schema  but   I have Added routes for Their Alternative routes like to search by authorName (instead of Name) , search by tags (instead of Category) , Search by Summary (instead of description).

**Comment by nishant0708** [comment]
> hey @SB2318 our Article Field doesn't have Any fields such as name , category ,description in schema but I have Added routes for Their Alternative routes like to search by authorName (instead of Name) , search by tags (instead of Category) , Search by Summary (instead of description).

**Comment by SB2318** [comment]
@nishant0708 I know, but I don't need them separately for this application instead of I need to use them as a search query.
With u r feature, I need to call 3 or 2 Api for that.
But my requirement only 1 api.

**Comment by SB2318** [comment]
@nishant0708  But still, please don't remove them as of now, because may they can help us in future purpose. 😇
As it is a level3 issue, I have only given you one extra task. 
Please try to complete it and commit your changes.
If u need any further clarification we can connect in VC.

**Comment by nishant0708** [comment]
hey @SB2318 Please Check it now and let me know changes i have not deleted anything

**Comment by nishant0708** [comment]
hey @SB2318  just a confirmation  let say i search  "health"  so i should get articles which have health in their title , description ,tags ,or in their Author name right?

**Review by SB2318 — APPROVED** [review]
Good Work!

**Pull request merged**
