### PR TITLE
Integrated React Native TTS

### LINKED ISSUE #294: 💡[Feature]: Integrate React Native TTS.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

*  **Install the Library:** 
First, you need to install the react-native-tts library

* Use it in the **PodcastScreen** with custom text 

* **Control Speech with Play Button:** Implement a function to handle the play button click, which will start or stop the speech:
image

* Control and display the speech progress, with the seekbar.
Track Speech Progress: Use the **Tts.addEventListener** to track the speech progress

image

### Use Case

**App Feature & Logic Building**

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by rushiii3**
#### PR Description
Please include a summary of the changes and the related issue. Describe your changes in detail.

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [x] Frontend
- [ ] Backend
- [ ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.
#294 
#### Add your Work Example
📷 Add a Snapshot
**ANDROID**
<video src="https://github.com/user-attachments/assets/bffc638f-315b-4347-b434-38c13e9e6c7e"></video>

**IOS**
<video src="https://github.com/user-attachments/assets/68287268-8cfd-494e-97fe-d3b7930b3ae5"></video>

#### Fixes (mention the issue number which this fixes)
#closes
#294 
#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Review by SB2318 — COMMENTED** [review]
Hello @rushiii3! 😊 Great to see you again! 👋 I totally understand that you've been working hard on your changes, and I appreciate that . However, I wanted to let you know that I've made some changes to the repository to keep it organized as it's grown a bit . I've merged some branches and deleted them to keep things tidy 🧹. To make sure your changes don't get lost, would you mind storing them locally and then deleting the repo?

**Comment by SB2318** [comment]
Hello @rushiii3! 😊 Great to see you again! 👋 I appreciate your contribution. However, I wanted to let you know that I've made some changes to the repository to keep it organized as it's grown a bit.  I've merged some branches and deleted them to keep things tidy. To make sure your changes don't get lost, would you mind storing them locally and then deleting the repo then forking again, please 🙏?

**Comment by rushiii3** [comment]
Sure, I had made a backup.

**Comment by rushiii3** [comment]
@SB2318, should I create a new PR?

**Comment by SB2318** [comment]
yes

**Comment by rushiii3** [comment]
Okayy!

**Pull request closed without merging**
