### PR TITLE
Hypertension Docs Added

### LINKED ISSUE #179: 💡[Feature]:  Hypertension - The Silent Killer  (English, Hindi, Tamil & Malay, Spanish)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hypertension - The Silent Killer 

Provide Both  Hindi and English version of the article.

Suggestion:
(i) First Write the English article,
(ii) Then translate it to hindi.

### Use Case

Article Collection

### Benefits

For Application

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by Damini2004**
#### PR Description
Hypertension Docs Added
#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#179 

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

Fixes #179

### CODE REVIEW

**Comment by SB2318** [comment]
@Damini2004  someone else are already assigned on the issue.

**Comment by Damini2004** [comment]
@SB2318 He/She might not active on this issue, so kindly assignedd the issue to and accept the pr.

**Comment by SB2318** [comment]
> @SB2318 He/She might not active on this issue, so kindly assignedd the issue to and accept the pr.

Okay, let's wait sometime for her response.

**Comment by Damini2004** [comment]
@SB2318 Sure !!!

**Comment by Damini2004** [comment]
@SB2318 If she will not responsed them, review and merge it before 31 july.

**Comment by Damini2004** [comment]
@SB2318 review the PR.

**Review by SB2318 — APPROVED** [review]

**Pull request merged**
