### PR TITLE
Mental Health Awareness and Stigma ( English, Hindi & Marathi )

### LINKED ISSUE #329: 📝[Docs]: Mental Health Awareness and Stigma
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to propose an article titled "Mental Health Awareness and Stigma" for inclusion in the repository. The article will explore the importance of raising awareness about mental health issues and how stigma affects individuals and communities. It will cover topics such as the impact of stigma on seeking help, the role of education in changing perceptions, and strategies for fostering a more inclusive and understanding society. This contribution aims to provide valuable insights and resources to help readers better understand and address mental health stigma. 

### Suggested Change

English, Hindi & Marathi

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
#### PR Description
This PR includes detailed articles on "Mental Health Awareness and Stigma" in English, Hindi, and Marathi. Each version covers various aspects including mental health understanding, stigma impact, barriers to care, and strategies for improvement. Additionally, relevant images are included to enhance the content.

#### Type of Change

- [X] Documentation update

#### Select your work-area

- [X] Documentation

#### Related Issue

Issue: #329 

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
closes #329 

#### Checklist
- [X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] I have checked for plagiarism and assure its authenticity.
- [X] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [X] I Agree

### CODE REVIEW

**Comment by Asymtode712** [comment]
@SB2318 Please check and merge this PR if it is good to go

**Comment by Asymtode712** [comment]
@SB2318 any changes required?

**Comment by SB2318** [comment]
No 😇, You did very well. 👍

**Comment by Asymtode712** [comment]
@SB2318 Sure

**Comment by Asymtode712** [comment]
@SB2318 Done with the changes please merge it now

**Pull request merged**
