### PR TITLE
[FEATURE]: Extension of Auth API : Email verification for user in backend  #80

### PR DESCRIPTION
**Pull request by nishant0708**
#### PR Description

- During user registration, a JWT token is generated and sent to the user's email for verification.
- Added nodemailer for sending verification emails, configured with environment variables.
- Created an email verification route that decodes the JWT token, verifies the user, and updates the user's status.
- Updated the User model to include isVerified and verificationToken fields.
- Added sendVerificationEmail function to dispatch verification emails.
- Modified the registration logic to generate and send the verification token.
- Updated .env file to include email service credentials and JWT secret.

#### Type of Change
- [y ] New feature (change which adds functionality)

#### Select your work-area
- [ y] Backend

#### Add your Work Example

https://github.com/SB2318/UltimateHealth/assets/101548649/7afd1a8e-3003-421f-97e5-a5138454961d

#### Fixes (mention the issue number which this fixes)
#80

#### Checklist
- [y ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [ y] I have optimized the file changes.
- [y ] I have added a snapshot of my work example.
- [y ] I have made a PR to the project's develop branch.

#### Undertaking
- [y ] My code follows the style guidelines of this project.
- [ y] I have performed a self-review of my code.
- [ y] I have commented my code, particularly in hard-to-understand areas.
- [y ] I have made corresponding changes to the documentation.
- [y ] I have checked for plagiarism and assure its authenticity.
- [ y] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [y ] I Agree

### CODE REVIEW

**Review by SB2318 — CHANGES_REQUESTED** [review]
First Email Verification then registration, Because email verification is one time feature, it can't happen with existing mail id, Let me know If you understand the process,

Ends up with the error, while testing

image

**Comment by nishant0708** [comment]
Okay

**Comment by nishant0708** [comment]
hey @SB2318  I have updated code Now in this latest commit, when user register his details are storing in temprory database where all the details of user who are unverified is stored and as soon as verifes his email his info will get stored in our main database . this will ensure our First Email Verification then registration

**Comment by SB2318** [comment]
image

**Review by SB2318 — APPROVED** [review]

**Comment by SB2318** [comment]
@nishant0708 please delete **package-lock.json** file

**Comment by nishant0708** [comment]
Hey @SB2318 I have removed package-lock.jsoon please check it

**Comment by SB2318** [comment]
@nishant0708 

image

can't merge

**Comment by nishant0708** [comment]
let me check

**Comment by SB2318** [comment]
> let me check

Please update your branch

**Comment by nishant0708** [comment]
Yes on it

**Comment by nishant0708** [comment]
hey i am rasing new pr it will work fine check that

**Pull request closed without merging**
