### PR TITLE
HIV/AIDS

### LINKED ISSUE #310: 📝[Docs]: HIV/AIDS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

HIV - Current Treatments and Research
@SB2318 assign me this issue

### Suggested Change

NA

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by revanth1718**
#### PR Description
I added detailed explanation on the topic - "HIV/AIDS"

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.
Fixes #310 issue

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#310 closes

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Comment by revanth1718** [comment]
@SB2318, kindly view this PR

**Review by SB2318 — COMMENTED** [review]
Please include those things:
(i) How can we stop spread of HIV
(ii) How can we help HIV community
(iii) HIV counselling and social awareness

**Comment by revanth1718** [comment]
View Updated PR @SB2318 mam

**Review by SB2318 — APPROVED** [review]
Thanks for your Contribution!

**Pull request merged**
