### PR TITLE
Create greetings.yaml

### PR DESCRIPTION
**Pull request by sanmarg**
Added for #33

### CODE REVIEW

**Review by SB2318 — CHANGES_REQUESTED** [review]
Please update your branch with main branch. Thanks for the great contribution!

**Comment by sanmarg** [comment]
If you merge into the main branch it will go to the main branch.

**Review by SB2318 — COMMENTED** [review]
image

Please update your branch.

**Comment by sanmarg** [comment]
done

**Comment by sanmarg** [comment]
Could you please add the labels to it considering its technicalities.

**Comment by SB2318** [comment]
> Could you please add the labels to it considering its technicalities.

Am sorry, I think only merged PRs are considered. Please ask them and let me know

**Comment by shikha123-ops** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me? I have implemented the language-switcher changes and would like to submit a PR for it. Thank you!

**Pull request closed without merging**
