### PR TITLE
Addition and Updating of Links in README.md and Learn.md files

### LINKED ISSUE #176: 📝[Docs]: Make the Content bulletins as clickable links
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The README.md file has links which used to help the reader to navigate to the required section with ease. The file has now been modified, giving it a totally awesome look. But the links under the [📌Contents:](https://github.com/SB2318/UltimateHealth?tab=readme-ov-file#pushpincontents-) redirect to nowhere. 

Moreover, certain new sections like [Our Vision:](https://github.com/SB2318/UltimateHealth?tab=readme-ov-file#zapour-vision), [ Code of Conduct:](https://github.com/SB2318/UltimateHealth?tab=readme-ov-file#-code-of-conduct) and the like have been added, which are not mentioned in under the Contents.

The Learn.md file has a [Table of Contents:](https://github.com/SB2318/UltimateHealth/blob/main/Learn.md#table-of-contents) with the titles listed out in the right order, but scrolling down each time to read a section listed way below poses a certain kind of annoyance to the reader.

### Suggested Change

Updating the links provided on the README.md file as per the modified file and adding the new headings under the Contents would allow for ease of access and upkeep of a well maintained README.md file

Appending links to the headers in the Learn.md file would also prove to be highly beneficial for those browsing through the file.

### Rationale

_No response_

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MaryamMohamedYahya**
#### PR Description

1. The Table of Contents in the Learn.md file have been modified to be links for easy navigation.
2. The Contents of README.md file are updated in accordance with the latest updates.

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 

- The headers in Learn.md file

    image

- Contents in README.md file
   
image

- As Project Requirements have been moved to a drop down, the subheadings are correspondingly listed under the same as listing them with the main contents does not work.

image

- The same has been done for the Getting Started section where subheadings are listed under the same dropdown because navigation from content under one dropdown to other did not seem to be supported.

image

#### Fixes (mention the issue number which this fixes)
#closes  #176

#### Checklist
- [x] I have updated my branch and synced it with the project's 'main' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's main branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Review by SB2318 — DISMISSED** [review]
Nice work!

**Review by SB2318 — CHANGES_REQUESTED** [review]
Good!
Please Squash or rebase your commits into single one.

**Comment by SB2318** [comment]
@MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?

**Comment by SB2318** [comment]
> @MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?

Kindly minimize those and ensure your task is completed by the 30th! Let me know if you need any help.

**Comment by MaryamMohamedYahya** [comment]
Please assist on how to do that. I tried a few online solutions but nothing's happened. 
Do I have to clone the repo ?

**Comment by MaryamMohamedYahya** [comment]
> > @MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?
> 
> Kindly minimize those and ensure your task is completed by the 30th! Let me know if you need any help.

Please assist on how to do that. I tried a few online solutions but nothing's happened.
Do I have to clone the repo ?

**Comment by SB2318** [comment]
> > > @MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?
> > 
> > 
> > Kindly minimize those and ensure your task is completed by the 30th! Let me know if you need any help.
> 
> Please assist on how to do that. I tried a few online solutions but nothing's happened. This is how I made my commits. I forked the repo and then made changes and raised PR. Did I have to clone the repo ? Should I close this PR and raise a new one ?

Okay, let you know

**Comment by SB2318** [comment]
> > > > @MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?
> > > 
> > > 
> > > Kindly minimize those and ensure your task is completed by the 30th! Let me know if you need any help.
> > 
> > 
> > Please assist on how to do that. I tried a few online solutions but nothing's happened. This is how I made my commits. I forked the repo and then made changes and raised PR. Did I have to clone the repo ? Should I close this PR and raise a new one ?
> 
> Okay, let you know

Go to terminal:

1. Checkout Your Branch .

2. Run the following command : `git rebase -i HEAD~221` [As you have 221 commits]
3. In the interactive shell, replace pick with squash (or s for short) for all commits except the first one. The first commit will be the one that remains after squashing.

For example,

```
pick  5ba7082  Update Readme.md
squash 5d37f5d Update Readme.md
squash 2649dca Update Readme.md
```
These line tells Git to keep the commit with hash 5ba7082 and message "Update Readme.md" (First Commit) as is. The pick keyword means keep this commit unchanged.
squash 5d37f5d Update Readme.md (Second commit): This line tells Git to squash the commit with hash.

The same things you have to done with rest 220 commits.

Keep the first commit (5ba7082) as is.
Squash the second commit (5d37f5d ) into the first commit.
Squash the third commit (2649dca ) into the resulting commit from step 2.
The end result is a single commit that contains all the changes from the original three commits.

### Note that the order of the commits is important. (The order in which you made those commits).


###Save and close the file. Edit the commit message, and then force-push the updated branch:

`git push origin main --force-with-lease` [For your case]

**Comment by SB2318** [comment]
> > > > > @MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?
> > > > 
> > > > 
> > > > Kindly minimize those and ensure your task is completed by the 30th! Let me know if you need any help.
> > > 
> > > 
> > > Please assist on how to do that. I tried a few online solutions but nothing's happened. This is how I made my commits. I forked the repo and then made changes and raised PR. Did I have to clone the repo ? Should I close this PR and raise a new one ?
> > 
> > 
> > Okay, let you know
> 
> Go to terminal:
> 
> 1. Checkout Your Branch .
> 2. Run the following command : `git rebase -i HEAD~221` [As you have 221 commits]
> 3. In the interactive shell, replace pick with squash (or s for short) for all commits except the first one. The first commit will be the one that remains after squashing.
> 
> For example,
> 
> ```
> pick  5ba7082  Update Readme.md
> squash 5d37f5d Update Readme.md
> squash 2649dca Update Readme.md
> ```
> 
> These line tells Git to keep the commit with hash [5ba7082](https://github.com/SB2318/UltimateHealth/commit/5ba70824c631766706149c4611a25962e0d36bd1) and message "Update Readme.md" (First Commit) as is. The pick keyword means keep this commit unchanged. squash [5d37f5d](https://github.com/SB2318/UltimateHealth/commit/5d37f5ddd84d295663e8c1d6316663afc8ac8b11) Update Readme.md (Second commit): This line tells Git to squash the commit with hash.
> 
> The same things you have to done with rest 220 commits.
> 
> Keep the first commit ([5ba7082](https://github.com/SB2318/UltimateHealth/commit/5ba70824c631766706149c4611a25962e0d36bd1)) as is. Squash the second commit ([5d37f5d](https://github.com/SB2318/UltimateHealth/commit/5d37f5ddd84d295663e8c1d6316663afc8ac8b11) ) into the first commit. Squash the third commit ([2649dca](https://github.com/SB2318/UltimateHealth/commit/2649dcab24baa058c8713bb231d7b901f528c27a) ) into the resulting commit from step 2. The end result is a single commit that contains all the changes from the original three commits.
> 
> ### Note that the order of the commits is important. (The order in which you made those commits).
> ###Save and close the file. Edit the commit message, and then force-push the updated branch:
> 
> `git push origin main --force-with-lease` [For your case]

If it doesn't work, let me know.

**Comment by MaryamMohamedYahya** [comment]
> > > > > > @MaryamMohamedYahya 🎉 I thought we were on a mission to lower those commit numbers. Can you please stay on this?
> > > > > 
> > > > > 
> > > > > Kindly minimize those and ensure your task is completed by the 30th! Let me know if you need any help.
> > > > 
> > > > 
> > > > Please assist on how to do that. I tried a few online solutions but nothing's happened. This is how I made my commits. I forked the repo and then made changes and raised PR. Did I have to clone the repo ? Should I close this PR and raise a new one ?
> > > 
> > > 
> > > Okay, let you know
> > 
> > 
> > Go to terminal:
> > 
> > 1. Checkout Your Branch .
> > 2. Run the following command : `git rebase -i HEAD~221` [As you have 221 commits]
> > 3. In the interactive shell, replace pick with squash (or s for short) for all commits except the first one. The first commit will be the one that remains after squashing.
> > 
> > For example,
> > ```
> > pick  5ba7082  Update Readme.md
> > squash 5d37f5d Update Readme.md
> > squash 2649dca Update Readme.md
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These line tells Git to keep the commit with hash [5ba7082](https://github.com/SB2318/UltimateHealth/commit/5ba70824c631766706149c4611a25962e0d36bd1) and message "Update Readme.md" (First Commit) as is. The pick keyword means keep this commit unchanged. squash [5d37f5d](https://github.com/SB2318/UltimateHealth/commit/5d37f5ddd84d295663e8c1d6316663afc8ac8b11) Update Readme.md (Second commit): This line tells Git to squash the commit with hash.
> > The same things you have to done with rest 220 commits.
> > Keep the first commit ([5ba7082](https://github.com/SB2318/UltimateHealth/commit/5ba70824c631766706149c4611a25962e0d36bd1)) as is. Squash the second commit ([5d37f5d](https://github.com/SB2318/UltimateHealth/commit/5d37f5ddd84d295663e8c1d6316663afc8ac8b11) ) into the first commit. Squash the third commit ([2649dca](https://github.com/SB2318/UltimateHealth/commit/2649dcab24baa058c8713bb231d7b901f528c27a) ) into the resulting commit from step 2. The end result is a single commit that contains all the changes from the original three commits.
> > ### Note that the order of the commits is important. (The order in which you made those commits).
> > ###Save and close the file. Edit the commit message, and then force-push the updated branch:
> > `git push origin main --force-with-lease` [For your case]
> 
> If it doesn't work, let me know.

This is what I get on giving rebase
fatal: invalid upstream 'HEAD~221'

**Comment by MaryamMohamedYahya** [comment]
I by mistakenly deleted first commit I guess...is it possible to open this pr again?

**Comment by SB2318** [comment]
> I by mistakenly deleted first commit I guess...is it possible to open this pr again?

Why not? And today you have solved one of the most important problem also.
I would like to suggest that you share your solution on this important GitHub topic, but not just here.

**Comment by MaryamMohamedYahya** [comment]
> > I by mistakenly deleted first commit I guess...is it possible to open this pr again?
> 
> Why not? And today you have solved one of the most important problem also. I would like to suggest that you share your solution on this important GitHub topic, but not just here.

Er..How?

**Pull request closed without merging**
