### PR TITLE
How to Prevent and Treat Osteoporosis

### LINKED ISSUE #241: 📝[Docs]: How to Prevent and Treat Osteoporosis
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Osteoporosis, or "porous bone", is a bone disease that weakens bones and increases the risk of fractures. It develops when bone density and mass decreases, or the structure and strength of bone changes.

I want to add detailed explanation on topic - How to Prevent and Treat Osteoporosis

@SB2318, assign me this issue under GSSOC'24

### Suggested Change

NA

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sreevidya-16**
#### PR Description
Added information on the topic - How to Prevent and Treat Osteoporosis

This PR fixes #241 issue

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Related Issue
#241 

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#closes

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Review by SB2318 — CHANGES_REQUESTED** [review]
Please modify this also, and add little bit more details (easy to understand) with every point.

**Comment by sreevidya-16** [comment]
I updated @SB2318, have a look on this PR

**Review by SB2318 — CHANGES_REQUESTED** [review]
In the diet section, try to provide a diet chart, If possible.
Not as a table, but as a detailed info, that what should you eat or what not.

**Review by SB2318 — CHANGES_REQUESTED** [review]
Since you mentioned that women are more affected by this disease, please include some details and prevention strategies that they can easily incorporate into their daily routines.

**Comment by sreevidya-16** [comment]
I updated @SB2318, have a look on this PR

**Review by SB2318 — APPROVED** [review]
Nice!

**Pull request merged**
