### PR TITLE
Delete user account from backend issue ID : #97

### PR DESCRIPTION
**Pull request by Kamaleshbala01**
Feature : Delete User Account from Backend
issue ID : 97
Work Area : Backend
Functionality : 
     user level account Delete : The user can delete their respective account form the database.
     API - request Body : {
                    password:"user respective password"
                }
             header : authorization : "token jwt_token"
             
      Admin level Delete : I created new model for an admin which follows : adminEmail and adminPassword 
                                       here it must manually add by the database admin or project admin where the password should be 
                                       Hashed using one way hash function by online and stored in database.

      API - request Body : {
                    adminEmail:"admin mail ID",
                    adminPassword:"admin password",
                    userEmail:"the user mail ID to be delete"
                }

#### Select your work-area
- [ ] Frontend
- [✔️ ] Backend
- [ ] Documentation
- [ ] Others

# Related Issue
Please provide a link to the issue solved if applicable.

# Add your Work Example
Screenshot_20240603_124355
Screenshot_20240603_124412

#Fixes (mention the issue number which this fixes)
#closes

# Checklist
- [ ✔️] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [✔️ ] I have optimized the file changes.
- [ ✔️] I have added a snapshot of my work example.
- [ ✔️] I have made a PR to the project's develop branch.

# Undertaking
- [✔️ ] My code follows the style guidelines of this project.
- [✔️ ] I have performed a self-review of my code.
- [ ✔️] I have commented my code, particularly in hard-to-understand areas.
- [✔️ ] I have made corresponding changes to the documentation.
- [✔️ ] I have checked for plagiarism and assure its authenticity.
- [ ✔️] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [✔️ ] I Agree

### CODE REVIEW

**Review by SB2318 — APPROVED** [review]
Great Work! 🎉
Thanks for your Contribution.

**Comment by Kamaleshbala01** [comment]
@SB2318 The PR is raised from the updated main branch so You can merge this any Time

**Comment by SB2318** [comment]
> @SB2318 The PR is raised from the updated main branch so You can merge this any Time

image

**Comment by Kamaleshbala01** [comment]
@SB2318 May I get you discord to clarify the doubt plz

**Comment by SB2318** [comment]
> @SB2318 The PR is raised from the updated main branch so You can merge this any Time

Your branch doesn't contain these 4 commits. Please check If I am wrong.

image

**Pull request merged**
