### PR TITLE
[FEATURE]: Create Tags or Article Categories API. #125

### PR DESCRIPTION
**Pull request by nishant0708**
#### PR Description
Made An Backend for Articles as Explained 

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [y ] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [ ] Frontend
- [ y] Backend
- [ ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot

Screenshot 2024-06-16 200440

Screenshot 2024-06-16 200533

Screenshot 2024-06-16 200626

Screenshot 2024-06-16 200642

Screenshot 2024-06-16 200716

#### Fixes (mention the issue number which this fixes)
#closes

#### Checklist
- [ y] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [ y] I have optimized the file changes.
- [y ] I have added a snapshot of my work example.
- [ y] I have made a PR to the project's develop branch.

#### Undertaking
- [y ] My code follows the style guidelines of this project.
- [y ] I have performed a self-review of my code.
- [y ] I have commented my code, particularly in hard-to-understand areas.
- [y ] I have made corresponding changes to the documentation.
- [y ] I have checked for plagiarism and assure its authenticity.
- [ y] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [y ] I Agree

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @SB2318 please Check this And let me Know if you Want This Api to work this way or not. Or want Any Changes

**Comment by SB2318** [comment]
> Hey @SB2318 please Check this And let me Know if you Want This Api to work this way or not. Or want Any Changes

Okay, will check!  Thank you! 😇

**Comment by nishant0708** [comment]
Hey @SB2318 Any changes??

**Comment by SB2318** [comment]
> Hey @SB2318 Any changes??

api path need to be change, will let you know with rest points.

**Review by SB2318 — COMMENTED** [review]
Nice Work!
Please add the necessary changes:

(i) This is not article schema, instead those are article tags.
so make sure you have change all the function name as well as routes.

createArticle => addNewTag
getArticles => getAllTags

updateArticle => updateTagyId
deleteArticle => deleteArticleTagByIds

articleSchema => articleTag

router.post('/articles/tags', ArticleController.createArticle); // change function name as well.
router.get('/articles/tags', ArticleController.getArticles);
router.put('/articles/tags/:id', ArticleController.updateArticle);
router.delete('/articles/tags/:id', ArticleController.deleteArticle);

*  Make Id dynamic.
image

although there is a dynamic id, generating at the time of new tag creation, but  here you need to implement an incrementor functionality.

instead of static field like
"id": "1"

Incrementor in sense, it detect the actual position of the tag in the array and it will be the index position.

* I can't understand the update method, and it is also not working, Please check once, You can use dynamic id also.

**Comment by nishant0708** [comment]
Hey @SB2318 so the tags should get updated by _id correct? And should also delete by _id??

**Comment by nishant0708** [comment]
Hey @SB2318 please check it now .

 And actually here update can be use to update tag name like if user have given tag with id 3 a name "tag3" and if want to change that tag name he could do it by using route /articles/tag/3 and in post he can send new name

**Review by SB2318 — APPROVED** [review]

**Pull request merged**
