### PR TITLE
Fixed #216

### LINKED ISSUE #216: 💡[Feature]: Caring for children disabilities article in hindi & tamil
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to convert this article into hindi

### Use Case

there is no hindi  version there

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Parth20GitHub**
#### PR Description
Please include a summary of the changes and the related issue. Describe your changes in detail.
#216 

#### Type of Change
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Review by SB2318 — APPROVED** [review]
Good!

**Review by SB2318 — COMMENTED** [review]
you haven't added tamil translation, do you want to add it so that it becomes a level2 issue.

**Comment by Parth20GitHub** [comment]
I think it should be level-3 for 2 docs

**Comment by Parth20GitHub** [comment]
Please update to level-3 , I will also do it in Tamil translation

**Comment by SB2318** [comment]
> Please update to level-3 , I will also do it in Tamil translation

Okay 😇

**Comment by Parth20GitHub** [comment]
Please check now

**Review by SB2318 — APPROVED** [review]
Nice work!

**Pull request merged**
