### PR TITLE
 [Docs]: Robot Assisted Knee Joint Replacement Surgery

### LINKED ISSUE #161: 📝[Docs]: Robot Assisted Knee Joint Replacement Surgery
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Reference:

(i) https://www.pennmedicine.org/for-patients-and-visitors/find-a-program-or-service/orthopaedics/knee-pain/knee-surgery/knee-replacement-surgery/robotic-knee-replacements

(ii) https://www.lifespan.org/lifespan-living/robotic-knee-replacement-surgery-right-you

(iii) https://www.orthobethesda.com/blog/robotic-vs-traditional-knee-replacement-surgery/

### Suggested Change

Mentioned above

### Rationale

_No response_

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by AsmitaMishra24**
#### PR Description
Added Doc on Robot assisted knee joint replacement surgery.

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [X] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [X] Documentation
- [ ] Others

#### Related Issue
#161 

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#closes #161

#### Checklist
- [X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X] I have optimized the file changes.
- [X] I have added a snapshot of my work example.
- [X] I have made a PR to the project's develop branch.

#### Undertaking
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] I have checked for plagiarism and assure its authenticity.
- [X] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [X] I Agree

### CODE REVIEW

**Review by SB2318 — COMMENTED** [review]
Please check AI percentage and please reduce it to 40%.
Good work!

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  IF this still pending can i please work 
@AsmitaMishra24  Are you working on that if not please tell me

**Comment by AsmitaMishra24** [comment]
> @SB2318 IF this still pending can i please work @AsmitaMishra24 Are you working on that if not please tell

@Ayushmaanagarwal1211 @SB2318, I will complete it by tomorrow. My exams are going on, so that's why it is delayed.

**Comment by Ayushmaanagarwal1211** [comment]
Ya ya i am just asking i just  thought that you are not online no problem

**Comment by SB2318** [comment]
> Ya ya i am just asking i just thought that you are not online no problem

New issues will come by today night. @AsmitaMishra24 you can take your time. 😇

**Comment by SB2318** [comment]
@AsmitaMishra24  please try to complete your work before 30th July.

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 please try to complete your work as soon as possible.

Yes, ma'am, I am working on it and will complete it today.

**Comment by AsmitaMishra24** [comment]
@SB2318, ma'am, I removed most of the AI content. Please review and let me know if any changes are required. Also, sorry for the delay, I was trying to complete it but my exam started.

**Review by SB2318 — APPROVED** [review]

**Pull request merged**
