### PR TITLE
Create PCOD_Unplugged:Unlocking_the_Secrets_to_Wellness.md

### LINKED ISSUE #293: 📝[Docs]: "PCOD Unplugged: Unlocking the Secrets to Wellness"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

"PCOD Unplugged: Unlocking the Secrets to Wellness"

### Suggested Change

"PCOD Unplugged: Unlocking the Secrets to Wellness"

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by arunimaChintu**
#### PR Description
PCOD Unplugged: Unlocking the Secrets to Wellness
Closes #293 
#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [ ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#closes

#### Checklist
- [ ] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [ ] I have optimized the file changes.
- [ ] I have added a snapshot of my work example.
- [ ] I have made a PR to the project's develop branch.

#### Undertaking
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have checked for plagiarism and assure its authenticity.
- [ ] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [ ] I Agree

### CODE REVIEW

**Comment by arunimaChintu** [comment]
@SB2318 Done! Please merge this

**Review by SB2318 — APPROVED** [review]

**Review by SB2318 — COMMENTED** [review]
Please add translations in different  available languages.

**Comment by arunimaChintu** [comment]
Done! @SB2318 Added translations in Hindi,Bengali, Tamil, Telugu and kannada... Please merge this noww

**Review by SB2318 — COMMENTED** [review]
Please create different files for each translations, and translate the whole  article.
You can select any two languages for translation.

**Review by SB2318 — APPROVED** [review]
Thanks for your contribution! 😇💖

**Pull request merged**
