### PR TITLE
Articles on OsteoArthritis added

### LINKED ISSUE #356: 📝[Docs]: The Role of Diet and Nutrition in Managing Osteoarthritis
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

How certain foods can help reduce inflammation and improve joint health and also how one can avoid knee replacement surgeries with proper maintainance of diet.

### Suggested Change

New Addition.

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Nayanika1402**
#### PR Description

Articles on OsteoArthritis added

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
Closes #356

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [ ] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Review by SB2318 — APPROVED** [review]
Hello @Nayanika1402 ! Thanks for your contribution! 🎉
Please include your name as an author.

**Comment by Nayanika1402** [comment]
@SB2318 Is there any changes I need to make?

**Comment by SB2318** [comment]
> @SB2318 Is there any changes I need to make?

No, Overall good content.  😊 
Please add your name as an author.

**Comment by Nayanika1402** [comment]
@SB2318 where to add

**Comment by Nayanika1402** [comment]
@SB2318 I have added the author's name.Kindly merge it.

**Pull request merged**
