### PR TITLE
[Docs]: Effects of music in mental health : The Impact of Music on Emotions, Mental Growth, and Meditation #162

### LINKED ISSUE #162: 📝[Docs]: Effects of music in mental health : The Impact of Music on Emotions, Mental Growth, and Meditation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

First, you must write the article yourself. However, I can provide you with some alternative use-cases to consider:

1. **Exploring the Impact of Sad Music:** Delve into the emotional and psychological effects of listening to sad music. Analyze how it can evoke different emotions, such as nostalgia, melancholy, or even a sense of comfort.

2. **The Power of Music for Mental Growth:**  Investigate the role of music in promoting mental growth and well-being. Examine different genres and their potential to enhance cognitive functions, boost creativity, and improve overall mental health.

3. **Harnessing Music to Control Your Mind State:** Discuss how certain types of music can influence and regulate our mind states. Explore how specific rhythms, melodies, and harmonies can help us relax, focus, or energize, depending on our needs.

4. **Music as a Tool for Mind Stabilization:** Consider the therapeutic qualities of music in stabilizing our minds. Explore the potential of music therapy techniques in managing stress, anxiety, or mood disorders.

5. **Music's Role in Meditation:** Examine the relationship between music and meditation practices. Discuss different genres and styles that can facilitate a meditative state, enhance mindfulness, and deepen spiritual experiences.

By exploring these alternative use-cases, you can offer readers a fresh perspective on the impact of music on our emotions, mental well-being, and spiritual growth.

### Suggested Change

Given

### Rationale

_No response_

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by nishant0708**
#### PR Description
Please include a summary of the changes and the related issue. Describe your changes in detail.
closes #162 

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ X] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [X ] Documentation
- [ ] Others

#### Related Issue
Please provide a link to the issue solved if applicable.

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#closes

#### Checklist
- [ X] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [X ] I have optimized the file changes.
- [X ] I have added a snapshot of my work example.
- [ X] I have made a PR to the project's develop branch.

#### Undertaking
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have made corresponding changes to the documentation.
- [X ] I have checked for plagiarism and assure its authenticity.
- [ X] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [X ] I Agree

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @SB2318 please review this pr and let me know if there are  any changes

**Review by SB2318 — COMMENTED** [review]
image
* Proper image is the assets of this article, make sure that all images are coming in the right way.
* Give suggestion that what music you need to listen during which time, based on people interest. (Title: **Music with self care**)

**Comment by nishant0708** [comment]
hey @SB2318 updated documentation with all the changes you asked for added music recommendations as well please see and let me know changes

**Review by SB2318 — COMMENTED** [review]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBAQDxAPEBUQEBUVEBAPDxAPEA8QFRUWFhURFRUYHSggGBolHRUWITEhJSkrLi4uFx8zODMuOCgtLisBCgoKDg0OGxAQGislHiUvLS0tLSstLS0tKy0tLS0tLS0tLS8tLS0rLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAJwBQwMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAABAAIDBAUGB//EADwQAAIBAgQDBgMECQQDAAAAAAECAAMRBBIhMQVBUQYTImFxgTKRoUJSsdEUI2JygqLB4fAHFZLxM0Oy/8QAGgEBAQEBAQEBAAAAAAAAAAAAAAEDAgQFBv/EACQRAQACAgICAQUBAQAAAAAAAAABAgMREiEEMUEiMlFhcRMU/9oADAMBAAIRAxEAPwDaWTJI0kyCfmn10iyRYxRJFkU9RHk2BJ5QKIq/wmBnYZ89Qk76/LpLNGplsDsZSwDfrD5ky9RAZdepllVpm0vK5YOpZjyJA6Ac5BXZlFhrc2t5HeUuI4saBbi+hHkN4iETYSrmViTsb+vnNSjVBNr8rj0mHgz4Lc9ST5dJfwb7fSJVqrJBIaHmY9Lm5vYcrbnzhEsdGqI+EECOAgiS/OA8RQiK0qBDDaGEC0QEMUBRQxWlQoIbRWgCKEiCRSghigCCGCFKNjoDChBDAYDTGmPMaZFMtBHRQOdQSZRGIJKsB6iSKIxRJUkD1ELrdSPKISQCBzmCbx26Pr6TTV7OR5TMw+laqp3ubfOWcS/2huPrOpISYt7sPf5zI4of1qA8kH4mXVrZrGZ3F2HelhyRRLWOyT6GIspHPN9Okt4WvaqqzD73b1vJUxBLhgdiJ3NSJdrSex9ZPh25TJwWJDgXMtq5FxzQ3H7SmZK0xDzkdJwwBHSSDf2hyT7SRY1hDeVDxHQLHQmwhiilQrRWhigKKK0NoAihigAwQmCAIoYoUIITBIpQQwQQBgMJghTY0x0EimxQxQOfSSqJEkmWBIskWRrJVkDxJBIxHiBgcbXu6y1ANGGvqJHVqg2PI6zV49hs9FrbrqP6zlaOIOUiaRG4Telhz3bFhqLXI6TNxFa+pNyd5br1bqSP7iZuIXYjTQTSkObSjrVNwPSSUmI9wPnKT1LHX5ySriQUAvYjnNuLjk6bg1cM29iOR6zVxWMC2YkAr16Tz1eIgG97EcxpG43jj1bKWOmg5XP3jM/+eZl1/rEQ6Sr2wdamSigIvs17k9BadhwlsSyh6pTX7Kg6e88y7EYIVsVd2JyajzM9hoUjbSbf89d6St5mNyp47vwaJQeE1bVrAXWnkax1/ayyLD4uo1d0suREHi1BZ2J09gP5hLB4oRWq0guZaKrnc7d4wzZB6LY/xCMpkVfFSdCrEjwiwBGh+RH0lnDT1pYn8rrVCoBYAX2kFfEsrgUzSqFhfuWfu6xH7F9D7/OO4fSLMzVC90QIA1wgIuWI5G9xr5CcXxfj2WqMJ+jriRToo5vmSqjuC5dHvceFkiMMe4hN/DvMPWWoCUJDLo9JxarTPRh/XY8o8MJzPDKddlSrh6zAoSGTEE1c66HKanxW16G06aiVq/sOAMwBvb8xOLYOX2+0tus9jDD3TDcX8xBPNalq+4WJifRQxRTkCKGKAILR0EKbFDFaAIITBIoQQxQppgjo0mFAxpjjAZAIoooVz6CTLIkkyQHrJBGLJBIHiOEaI4QCRcEHnOC4lS7qs68g2nodZ3t5y3ajDePNb4xofMbj8JpjntzaOmIGuDyP4yCo/XSR1bj2ldq/KemKspsgxRIOkpVK/lLj1AZTxFXyWb1Z2VKlTXn7SxhsM7I9XXwMiaj7VQPb/wCfrKtTEnlYegtOn7EUlxFLG4W/iqIlRNdS1MkfQsn1m0QzmTOweICYhgOth1PmZ7Dha909p4kMNVwVYiqjUn3sRo4+8p5zol7bd2oFwb/MCczExO21bVmupegUcZTyV0HidXZv3rqCPy/hkvZ7CClhqCuQGCBqnnUbxN9SZznCsZSqgVEYX+8DYjyMuvj25kkdZzz/AC1/z36b9WopJC7HQ/nOM4b2WxZrYqpW7lO+cBWVs5FFFVVsOVwu2k2qeMEtLXHUj3iL7OM17hcw1GnQTKW2GpO7E7kzmMPxdauPcUWIagoDLfw1V3KnzG4g41xvelhUNSoRq1rhb6XnOdneztem9TEOailiQ2XKTfW+hElrRpIid/16bS41SPhY5DtZgV16ay0Vzag+4nnCYvDoGy4PEVraVHepUpknzF/xAknAO15pMKdbMEJ8JY5imvwlufrOYtNo+qOmcxET1LviWXcX8xv8oUcHY+3P5R+FxKVVDKQbjlDVwyncTO3jRPdVi/5NtFImpOvwm/k2v13jf0q2jqV8x4hPPbHavuHcd+k0USsGFwQfSKcAGCOgkUI0x0BgNiiikdBGmOjTCgYDCYJAIoooVgLJVMhWTLAlWSiRLJRIHiOjI4QE2xmdxqh3tE23HiHqJpSsxynKdm2/qJYHB4inrroeszcRTF9x+AnRcRo5KpQ7fZ9OUxsXRBzW0PKeqlmVoZlbDaX19iplCth+gP8AEw/AS9iKP3fcWF5Sq0ydyZ6qywmFKoirucx6Db3Mm4PjquHxFPEUzZqZ8K/ZYHQq37JB1je412+WpMcFN8qjU6aa+02iXEw9rwlfB8XwYFVSAw3YFalCp5Pa3p1HLlPNe1H+nuOwrXo0zi6bsAj0FuwzGyh03XffUeYleljKlBTUo1XpFEVQ9NitzmLEdGF2tY3Gk6jhfbPF0TSXFFXDWz1KKmnVXw5tUByNyB0FtZ3Fon24msx6czwbs/xTv1w64bEUXJ+Ksj0qIUDVjUtYj0v5T1rhvZJqdMCtiu8bmRTCrfpq1z9JW4b2ypYl6a0qwcZWOV0ekxI7u9swFz+sT2ebJx1Q9B5ZR85Zx1n2sZL19S5TtJwqrhypRgVc2Vxe2bexHI6GUF4bxCpYBlIPMkgATR/1G7SJh8Mgq6vUqLkVR4iEZS7W6BSdepEHZ3tnhKiqA+vQiee+OKz+nqx5ZtXv21OBcNTCpZrM5N3b7zS9ghmDg/aJ/G4/H6SZe6qjMLG/MGMKZGAGl+caJ7UqVEBjmAuNDpuOhlPivZ6hXQ5VAvsQNjNXF087DLfUWJHI/Zb03HuIcPQKAjqddb69Zpi1E8Z9Ms1ZmvKPbz3B8RxPCqoSrmeiTodSU/tPTeGcTp10V0YMGFwQbgzK4vwyniKZRxuNOes4jhprcNqsmrU81yn7J+0vnO8mLj3DHFl5/TL1qR1KIMocK4klZA6MGBmiH6TLqW3cM2vh2XxU9CNx1/OSYTEd4t9iDZh0YTRsCJmq6iq6AWuuY+oNvy+U8efFEfVDWt+XUp4DDAZ5XQQGGCFCCEwSKEaY4wQ6NghMEgEMUUDnkElSRrJFhUqyUSJZIJBJCsaIRAfIcXSzL5jUSUGGUczxqiXAP2l+FvvDmp85z9db6/56GdtxDChgbc9wdj5+s5XHYVlJuD63vNcdnNoYVenK1WmLa3mv3d9Dp62jHo0V+Nl9jeemtmUw59iW8Ki3W39Tylyhg8i5qh7tPtNsxH3Vvtfr8pcq46imlNCzciRpfymVVVqrB8UxsDcUgbM3r90ee83ids5jSzhk/SXDsBTw9H4QRYOy8rdOv5mLG4lQHqEnxXCX3yH439SdB7yLG47QZgFRR4aS6Cw2B6L9T9Zg4vFPVJY7chtbpNKxtxM6GrxFu7qU8q+M3FTxB6d2psQtjbejT3GljbeX6HbPiaKFXGVbWt4lpVG/5OpP1mFlLHSbfZvgb4iqqe7NuETm3ryA6mbbZa+T+F8MxfFMTmqVKtQ28dV8z5V5AdB5Caq9k8RhyaihmRXsGTf3HKeocKwq0URKaqqgWUWGYfxDmTf3M1aWEp1FKuWN9wQt/wAJMmPJH8dYcuO3Xy824ZxipTGjMLbqQZ0eB7RLU8NWolMfeZtD7bzXxHZPDvsai+mX8pHQ7KYemds/74F/ppPNwl7YvVLh+0eFTwU3NXTfJUN/cLLCcTRte8Hp4V+ebWWaPDaaDwKF/d0kddLA5gD924DWPKaRFvTO011MmmuNyygHmWWZ/GcCtdNPiHwsBf8A7mh+jqB8IGnLw/hGMFtaxJ6/3numOnyotqXAYGticLVYIMpv8FzkqDqL/CfKdVhe1QI/WK1NhuDLWN4UtVDe2a5NxyJ5CYeGZQ5pV0Riht41B05bz5fkTbFPrp9PBaMkfttjtYiLm0byB1PpNDhKu2avVGVqtrId6aDYHzN7n26SvgqVBbFKVJbagrTQEHrcCaSvPFfLNo0346TQQAxTNCMBiMRgNMUUUjo0wRxjYUDBCYJAIYIoVz6yZZAsmUwJVkgkSyRZBIIY0RxgKOEbFeA2qJjcRoXvNppTxCXlHIV6GsqVMOOk6LF4bymbWpWm1buZq5/EUmGxPtp+EzKpYbWHnz+c6PEpMbF056qWZWhkVEJ3/ONelpYe/UyzUW0jIm8Sy0jp0wo0nqnYjgRo4cVHVS1a1TqQlvAPkb/xGeXhSZ7R2cxSthMMb2PcoLXtqqgEX66TfBrmw8j7NQvZOW3kbydWI19L+shqMOdxbmQdP4toM5toQ3mCDm9+RntfP2uLiCDrr/WTfpCmUUcMt+m/LaQPWYt3aaG13a18gOwH7R19N+l85xVlvXyLx8tV8WoGmv0lOsxZlDH7V7AbAa/l84yhRCa3N+hJPuTzklIbsdz9B0iMcR6SctrezqhjTGvvIsTiBTW+99AOp6TtmnDWnKdsVyVaVZdMwyt6jUfQn5ToaYYAX1dza3Jf+pi9skvhx5YhFHtTcn8Z4/Krur1+LbVjOEcRuBczpcPWvOH4PSN512CFgJ8O0al9b3DWRo+QUzJhI4mBiMEMqGxRRSOgMbHGNhQMEMBkAiiihXOrJVkCmTJCJVMlUyJZIkipBHxghvAMMAMUBGRVFkpjCIFGtTlKthgZrOsruku1c/icFMvE8PvynXtQvOexPaDBq7oz/wDjYKzWFrnprc+oE2xzafthxbjHthvwq8C8I8p1mCOHrC9GpTfyVhf5by2vDh0nU5rR1KcIcnQ4MOk6vs8xojumHha+W+19yv8AWXhw0pYMpFxcXHKSV8FdbbHcHoRsZcfkWpeJlzkxReulvuE3CC5+6oU/MRjYRb5rVAf3rn6m0r8Pxma6t4WXRh5/lNFd/XYc5+greJjcPiWpMTpTPeU87ZWcEXyrbNmHlfW+2/SHhlUPTDj/ANnib987qfTb2m1Rwotrr+AmTjMH3Lmoi6N8agfziZznjbavjTx/axm/tCW5yuK4IBve/OR1cSFv6zXbDWlh3CgsTKWC/WuarbLogP1aU8RXaoyoDuduXrNCoQoFJN7a2+yvNj6wb0moHMWqnYAhPQbn/Okyu0FMtQVbaj9afK5H9Gb5TTxWiBB9ohR+7z+l4Hph+8J1DHIP3VBB/mLfKefyI3SYb4J1eJY3B6GgnQUEtKXD8Pl8J3Bt8pqos/PT7fa2egkqxiiPEOZGKIwQhRRQGFKNMJgMKbAYTBIBDBeKFc0hk6GV1MmUwiwsesiQyQSKkWOjUjoCEcDGxQCYIooDWEjZZNARCsrjlCs+HqLhiBUYWW5tpzseRtPJcfwbEUD+vo1VF9Wy3UjnZhpPcLR4Wb4s84/hlkxxd5F2i7P0Ew9PGcOqVmUWzq5GcXHxKVA9xNT/AEr4ziK2NSjWrtUpCm7ZXAZrqBbxHW2s7X/a6dCoa1OndWJNWkuouftqvXqJDwLgeCw2JGMosE71WWxYd3diG06HTae6mWuSO4ZWpNZ3C7xLtNQ/3Slw4B2d1FnFsqNZmyn2WbuMNM1kw+dc+TNkuM+Ta4HScLwjhgq9pKmJJBSnRLIetTKqfgzS7hGNTtPVqZvDQwOXyLMV8N/cn2nc4q23+9bc8rQk7Qq2GqNURc5A1W+XP9258pQ4Rx5mOaobk78reQHISLHriK/E8a5rg0FsiUc18xCr4gOVjf1nPY3NRckbE6iYcprP+e+vhpERvlMdvYeHYgOoI5yzXphhOK7F8YDKEJ9J2yNcT00tuHF66ncOR4hT7hyxJFM3JABJDclUDr0lGgz1SWsVW+o0JY/cXqep2E6viWGDggi95lKjKSFAz83YKFReWVQNT/l56cF9/TLx+TSY+qFXC4VlYkkd4dWI1Wkp2UX3PtNGigUae5JJJPUnmYKdDKNz1JO7HmSZFWxFrBRmJ+FfvH7x6KOs9Tw7B6t6rEa90v8AO2w/D5y3lCqo6W169TKlGnlst7knM7dW3v8A2lqpsZhl7hvi6lMF8V+oEtqJVpnQeX+GW0M+H5NOOTf5fVw33X+CBAI6NM87WBvFBFCjeCKCAjGmExsKRgiMEilFGxQjmgZKhkCyVJRYWSrIVkqzkSqY+RCPEKIMMaI6AoDEY2A68F4DG3gSqY8GQpHwJQZica4MXV+4Hx6vTuApYah1voGv85sAx4M6raazuEmNuCUvSpVTXKpV8Ipi9jmB1BPLS8lo40U8K4qVKaValbNkY7rlC6mdw1BG+JEb95Q34zMx/ZTBV/joKp+9SvTYf8dPmJ6q+THzDiYn4YXZjiWHRHLhS1ye8/LylyvwlMepqUSEJW9iPCTr8pwnaHArhcS1CmzlRb4yCfoBO/7E1CgABvcDf0m+onUuYne3OpwPH4KoHFJnUHU0jn+m/wBJ6LwHiPeopNwbahgQQfQy9UbSQtTB1tNNanpzvrUrla0z8TTv4kOo2O8gq4dd9fneRuuUXXT00jlO9nGJjSnVxovk/WMeZyA29tvnJsPTUXbK4J3LkFm+UWG8Tm/Nb++0fW5/s7T6WPJypt8jLi4Xmo0ObdTJW1FupjFFh7RxOhM5t6Ws/UlpHT3Mnw76W6aSsOnlHUTY+up9Z83zKbpv8Pd49tW0vXggvDPmPaV4Y0QwpQExQGFIxphMEgEBMUBgKKNigf/Z


Replace this kind of links, they are not coming. 

Either download the images in assets or give https links like this.

https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL211c2ljLWFuZC1oYXBwaW5lc3MtMy5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjI5MH19fQ==

**Comment by nishant0708** [comment]
Okay @SB2318 i will do it

**Comment by nishant0708** [comment]
Hey @SB2318 it should be fine now

**Review by SB2318 — APPROVED** [review]
Nice Work! 👍

**Pull request merged**
