### PR TITLE
Health Myths Debunked: What You Thought You Knew

### LINKED ISSUE #251: 📝[Docs]: Health Myths Debunked: What You Thought You Knew
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I want to add information on the topic - Health Myths Debunked: What You Thought You Knew

@SB2318 Please assign me this issue under GSSOC'24

### Suggested Change

NA

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sreevidya-16**
#### PR Description
Added matter on the topic - Health Myths Debunked: What You Thought You Knew.
I added very detailed matter, so that beginner's can also understand about the topic.
#251 issue is fixed

#### Type of Change
- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [x] Documentation update

#### Select your work-area
- [ ] Frontend
- [ ] Backend
- [x] Documentation
- [ ] Others

#### Related Issue
Fixes #251 issue

#### Add your Work Example
📷 Add a Snapshot

#### Fixes (mention the issue number which this fixes)
#251 closes

#### Checklist
- [x] I have updated my branch and synced it with the project's 'develop' branch before making this PR.
- [x] I have optimized the file changes.
- [x] I have added a snapshot of my work example.
- [x] I have made a PR to the project's develop branch.

#### Undertaking
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have checked for plagiarism and assure its authenticity.
- [x] I have read and followed the code of conduct for this repository. I understand that violation of this undertaking may have legal consequences.

- [x] I Agree

### CODE REVIEW

**Comment by sreevidya-16** [comment]
@SB2318, View this PR and if you require any changes, let me know otherwise kindly merge into main

**Review by SB2318 — CHANGES_REQUESTED** [review]
Mention source of the article, reduce your commit number.

**Review by SB2318 — CHANGES_REQUESTED** [review]
Include The following Myths:

* ## The '5-second rule'
* ## Leprosy is highly contagious and can be contracted by casual contact.
* ## Once you have chickenpox, you can never get it again, and it’s harmless.
* ## Smallpox can be spread through the air, and vaccines do not work.

Please include the Analysis of the truth of each myth (Existing & newly add)

**Comment by sreevidya-16** [comment]
I added Sources @SB2318 mam
At present, if I discard my commits(to reduce number of commits), then it will discard my newly added files. So please don't mind it now mam.
From next PRs onwards, I will reduce my commit number mam, sorry for that @SB2318
 I won't repeat it again

Once view updated PR @SB2318

**Comment by SB2318** [comment]
> I added Sources @SB2318 mam At present, if I discard my commits(to reduce number of commits), then it will discard my newly added files. So please don't mind it now mam. From next PRs onwards, I will reduce my commit number mam, sorry for that @SB2318 I won't repeat it again
> 
> Once view updated PR @SB2318

nothing will be discarded, But try to complete the rest requested changes.

**Comment by sreevidya-16** [comment]
I am having college exams mam
Sorry for delay 
I will complete it by tomorrow evening @SB2318

**Comment by SB2318** [comment]
> I am having college exams mam Sorry for delay I will complete it by tomorrow evening @SB2318

sure! take your time.

**Comment by sreevidya-16** [comment]
@SB2318, I updated this file mam
Once take a view of updated PR and if any changes required, let me know mam

**Review by SB2318 — APPROVED** [review]
Great!

**Pull request merged**
