### PR TITLE
Updated Branch and completed all tasks for Login page Development #85

### PR DESCRIPTION
**Pull request by iamworrell**
Validation
Screenshot (607)

Api Call
Screenshot (606)

Stringify and Store Data
Screenshot (609)

Output Error to User
Screenshot (608)

### CODE REVIEW

**Comment by SB2318** [comment]
Please join in VC.

**Comment by iamworrell** [comment]
@SB2318 I'm confused what do you mean by VC? Also, will this pull request be accepted?

**Comment by SB2318** [comment]
> @SB2318 I'm confused what do you mean by VC? Also, will this pull request be accepted?

discord voice channel, need one urgent discussion. please ping in the project channel

**Comment by SB2318** [comment]
> @SB2318 I'm confused what do you mean by VC? Also, will this pull request be accepted?

Off course

**Comment by iamworrell** [comment]
@SB2318 Do you have an invite link to the server?

**Comment by SB2318** [comment]
> @SB2318 Do you have an invite link to the server?

Have you participated in **GSSOC** program as a contributor?

**Comment by iamworrell** [comment]
No I haven't

**Comment by iamworrell** [comment]
@SB2318 when will I be added as a contributor?

**Comment by SB2318** [comment]
> @SB2318 when will I be added as a contributor?

In my repository today. 😇

**Review by SB2318 — APPROVED** [review]
You're welcome! Thank you for choosing this open source project and I greatly appreciate your valuable contribution. Congratulations on your job  and well done! 🎉

**Comment by iamworrell** [comment]
@SB2318 Hey I thought i would be a contributor but when I look on the project my name is not there.

**Comment by SB2318** [comment]
are u sure?

**Comment by SB2318** [comment]
> @SB2318 Hey I thought i would be a contributor but when I look on the project my name is not there.



image

**Comment by iamworrell** [comment]
ok thank you

**Pull request merged**
