### PR TITLE
Creation of .env file (Issue #23) and Project Restructure (Issue #24)

### PR DESCRIPTION
**Pull request by jaickeyminj**
Hi @SB2318 ,

I have completed the changes for issue #23 and #24. 
**Please review it and let me know if more changes are required.**

I have added a .gitkeep file in the Ultimate_Health_Frontend folder because it was not allowing me to push an empty directory.
I am attaching screenshots for your reference.

image
image

### CODE REVIEW

**Review by SB2318 — CHANGES_REQUESTED** [review]
Please separate the front end and backend content in each folder.

Front end will contain the front end part only and backend will contain the backend part.

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

I may need more clarification regarding your latest comment.

Here's a summary of what I have done.

1. Created a **Backend and Frontend** folder (#24  Screenshot is attached above)
2. Created a **.env** file inside the **Backend** folder, which will be consumed by the backend server (ExpressJs #23 ).
3. Created a **.gitkeep** file in **Frontend** folder because it was not allowing to push an empty directory.

As per your previous comment the FrontEnd and BackEnd code will be segregated in their respective folders.

Please let me know if you want me to initialize both folders with sample code to avoid confusion.
Thanks!

**Comment by SB2318** [comment]
### Before Your Changes

**Local Effect**

image

**Local Effect FrontEnd**

### With your changes,

**Local Effect:**

image

**Local Effect FrontEnd**

image

**Comment by SB2318** [comment]
@jaickeyminj Let's connect on discord server. I will explain there.

**Comment by jaickeyminj** [comment]
Lets talk over on Discord Server @SB2318 
Discord Handle - jaickey09

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

Please review the changes. I have copied all the files from respective branches.

image


image

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

Please review it at the earliest.
Thanks!

**Comment by SB2318** [comment]
Check failed

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

Check has failed due to you repo key which was located inside the node modules folder (**node_modules/debug/.coveralls.yml**)

Please clarify whether node modules should be commit into the folder or not.
It is not a best practice to add node_modules folder into repo because of its size.

Please reply at earliest.

**Comment by SB2318** [comment]
Please add a gitiginore file, and mentined there node modules.

**Pull request closed without merging**
