### PR TITLE
Added CONTRIBUTING.md

### LINKED ISSUE #19: Missing CONTRIBUTING.md File in Repository
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #19 and #38

### CODE REVIEW

**Comment by SB2318** [comment]
@suhanipaliwal  Please check this document once, and include some points.

Your previous work was outstanding! 
Please refer the document. 
https://docs.google.com/document/d/1MNn0CA0HjZNbrQ9y-L7nr-NCFO4yHAB1eOL41gSdhbM/edit?usp=sharing

**Review by SB2318 — CHANGES_REQUESTED** [review]
@suhanipaliwal Please check this document once, and include some points.

Your previous work was outstanding!
Please refer the document.
https://docs.google.com/document/d/1MNn0CA0HjZNbrQ9y-L7nr-NCFO4yHAB1eOL41gSdhbM/edit?usp=sharing

**Review by SB2318 — COMMENTED** [review]
image

Please update your branch.

**Comment by suhanipaliwal** [comment]
Done

**Review by SB2318 — APPROVED** [review]
Well done💗

**Pull request merged**
