### PR TITLE
Designed Signup Module

### PR DESCRIPTION
**Pull request by ParthNakum21**
Added SignUpScreen. #61 

s15

s14

### CODE REVIEW

**Comment by ParthNakum21** [comment]
Added Signup Module. #108 #61

**Review by SB2318 — CHANGES_REQUESTED** [review]
You have done a great job! 🎉

But here are some little modifications.


* 
 HomePage
  
 It has destroyed one of the existing features:
 **Issue  Number** #63  
 **PR Number**    #93 
 So make it as previously, but you can keep the signup button for your tasks as of now.

*  **Alignment Issues:**
   
SignUpPage1

First of all, reduce the top-margin of the text view.

Create another box inside the white box like I have painted,  and put your content there.

For your reference:

image

*  **Third: Dropdown issues:**
 
Dialog

It is not a dialog modal make it a dropdown menu.

For your reference:

https://www.npmjs.com/package/react-native-element-dropdown

* Commit your changes and update your branch.

**Comment by ParthNakum21** [comment]
I have made all the changes you mentioned.
- Removed Login button
- Fixed Alignment issues
- Fixed Dropdown issues

**Review by SB2318 — CHANGES_REQUESTED** [review]
* Set Click action on dropdown selection, 
for **general user**  selection, the button text will be **Register**  not **Continue** (Now, nothing happens) and it will not navigate to the doctor screen

* Make password secure text entry dynamic with eye icon,(it is a **level3** issue.)
* Ensure you have not jumped to the second page when all fields are empty or at least one field is empty.

Please commit to the rest of the changes as soon as possible.

**Comment by ParthNakum21** [comment]
I have made all the changes you mentioned.
 - Set click action for dropdown (Continue - Doctor, Register - General User)
 - Secure text entry of the password with eye icon.
 - Show alert if any field is empty.
 - Wrapped whole content in ScrollView.

**Review by SB2318 — APPROVED** [review]
Great Job!

**Comment by Vipullakum007** [comment]
hey @ParthNakum21 , please can you tell how to run this project i can't open main home page because this is my first TS project can you help me?

**Comment by ParthNakum21** [comment]
> hey @ParthNakum21 , please can you tell how to run this project i can't open main home page because this is my first TS project can you help me?

Sure!, Please share your Discord ID.

**Comment by Vipullakum007** [comment]
> > hey @ParthNakum21 , please can you tell how to run this project i can't open main home page because this is my first TS project can you help me?
> 
> Sure!, Please share your Discord ID.

vipul#7739

**Comment by ParthNakum21** [comment]
> > > hey @ParthNakum21 , please can you tell how to run this project i can't open main home page because this is my first TS project can you help me?
> > 
> > 
> > Sure!, Please share your Discord ID.
> 
> vipul#7739

I am not able to find you on discord. 
Please ping me on discord. 
ID: ParthNakum21

**Comment by Vipullakum007** [comment]
> > > > hey @ParthNakum21 , please can you tell how to run this project i can't open main home page because this is my first TS project can you help me?
> > > 
> > > 
> > > Sure!, Please share your Discord ID.
> > 
> > 
> > vipul#7739
> 
> I am not able to find you on discord. Please ping me on discord. ID: parthnakum21

try vipul_lakum_1

**Pull request merged**
